### ISSUE TITLE
Feature - Main Menu

### ISSUE THREAD

**Issue by rainbowshrimp** [rainbowshrimp/poke-battle#1]
#### Description

The main menu feature is the menu located on the first screen the player sees. It also serves as a navigation point for the player to use different features of the extension. 

The main menu will also display the different locations in game based on where the player is navigating to in their browser. 

The main menu will also display the amount of pokemon dollars the player has acquired through battling in game npc.

The main menu will display the first pokemon in the player's team and additional captured pokemon in their team. Along with the total and remaining amount of pokemon in the pokedex.

#### Files

The files that would require development are the following:
- ```menu.html```
- ```menu.js```
- ```_menu.scss``` 

#### To Reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.

#### Tasks

- [ ] Write Sass to style the menu
- [ ] Update the HTML to provide reference links in the ```href=""``` to other features in 
- [ ] Write JS code to do the following:
              - display/store the location
              - display/store trainer info
              - display/store pokemon team info
