### ISSUE TITLE
Feature - Locations

### ISSUE THREAD

**Issue by rainbowshrimp** [rainbowshrimp/poke-battle#3]
#### Description

The location feature is where the player will encounter wild pokemon. The type of location(grass, water, ground, etc) will be determined by where the player is domain the user is currently on. 

For example if the player is visiting youtube.com then the location will be a city and the type of pokemon the player will encounter would be normal, ghost, and steel. 

#### Files

The main files that would need development are:
- ```location.js```
- ```wild-encounter.html```
- ```_locations.scss```

#### To Reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.

#### Tasks

- [ ] Write HTML to structure the layout of this view and class name for styling
- [ ] Write Sass to style those elements 
- [ ] Write JS logic to meet the expected behavior described in the description
