### ISSUE TITLE
Feature - Battle

### ISSUE THREAD

**Issue by rainbowshrimp** [rainbowshrimp/poke-battle#4]
#### Description

This feature is the main battle screen the player will see when facing any battle situations(wild encounter, gym battles, etc).

On this screen the player will have four options to choose from.
     - Fight - where the player can select one out of four moves to use against enemy pokemon
     - Bag - Where the player can select an item to use on the enemy pokemon or their own
     - Pokemon - Where the player will have the option to switch to another pokemon
     - Run - Where the player can take a percentage risk to run away from wild encounters

#### Screenshots
Here is an example of the traditional battle menu from old pokemon games. The feature will have a similar display.

https://images.duckduckgo.com/iu/?u=https%3A%2F%2Fs3.amazonaws.com%2Fcolorslive%2Fpng%2F153212-UhZXgSh-30-1dTUY.png&f=1

#### Files

The main files that will need to be edited are:
 - ```battle.js```
 - ```_battle.scss```
 - ```battle.html```

#### To Reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.

#### Tasks

- [ ] Write HTML to structure the screen for styling
- [ ] Write Sass to styles for the battle screen and the pokemon that will be displayed
- [ ] Write JS logic that will allow combat to take place based on the description.
