### ISSUE TITLE
Feature - Pokedex

### ISSUE THREAD

**Issue by rainbowshrimp** [rainbowshrimp/poke-battle#5]
#### Description

This feature will keep a record of all relevant information on pokemon that player has captured and display them on screen

#### Screenshots
Here are some examples of pokedex found in traditional games. The pokedex for this chrome extension will follow a similar format.

https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.vizzed.com%2Fvideogames%2Fscreenshots%2F7%2F73494%2F70938%2FPokemon%2520Black%2520Version%25202_6149%2520-%2520Pokemon%2520Black%2520Version%25202%2520(DSi%2520Enhanced)(U)(frieNDS)__101201434214597-full.png&f=1

https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fstatic1.wikia.nocookie.net%2F__cb20120428225058%2Fpokemonessentials%2Fimages%2Fe%2Fe1%2FPokedexInfo.png&f=1

#### Files

The files that will be edited are:
- ```pokdex.html```
- ```_pokedex.scss```
- ```pokdex.js```

#### To Reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.

#### Tasks

- [ ] Write HTML to structure the view and prepare it for styling
- [ ] Write Sass to style the pokedex 
- [ ] Write JS Functionality to pull data from PokeAPI and record captured pokemon
